# Submission

### Load all other models made and create the final submission csv for that score.

### Import Libraries

In [2]:
from pathlib import Path
import sys
sys.path.insert(0, str(Path.cwd().parent))

In [3]:
import joblib

from src.config import MODEL_DIR, SUBMISSION_DIR, DATA_DIR
from src.data import load_test
from src.preprocessing import apply_preprocessing
from src.submission import save_submission

### Load Test Data

In [4]:
test_ids, X_test = load_test()
print(X_test.shape)

(299844, 21)

### Baseline Model - Logistic Regression

In [4]:
saved = joblib.load(MODEL_DIR / "logreg_baseline.joblib")
state, model = saved["state"], saved["model"]

#### Necessary preprocessing

In [5]:
X_test_encoded = apply_preprocessing(X_test, state)
print(X_test_encoded.shape, X_test_encoded.isna().sum().sum())

test_proba = model.predict_proba(X_test_encoded)[:, 1]

(299844, 39) 0

#### Submission

In [6]:
save_submission(test_ids, test_proba, "baseline_log_reg.csv")

Saved to: C:\Users\Bharat\Desktop\remaining-2026\Career-Tracks\Track 01 - Data Science\Relevant Projects\airline-satisfaction-prediction\submissions\baseline_log_reg.csv
count    299844.000000
mean          0.443881
std           0.394629
min           0.000035
25%           0.043513
50%           0.320346
75%           0.893377
max           0.999726
Name: satisfaction, dtype: float64

            id  satisfaction
0       699635      0.113779
1       699636      0.642731
2       699637      0.506373
3       699638      0.042798
4       699639      0.001065
...        ...           ...
299839  999474      0.447737
299840  999475      0.037892
299841  999476      0.093245
299842  999477      0.115596
299843  999478      0.004937

[299844 rows x 2 columns]

### Experiment - 1: one-hot encoded ratings

In [7]:
saved = joblib.load(MODEL_DIR / "logreg_onehot_ratings.joblib")
state, model = saved["state"], saved["model"]

#### Necessary Preprocessing

In [8]:
X_test_encoded = apply_preprocessing(X_test, state)
print(X_test_encoded.shape, X_test_encoded.isna().sum().sum())

test_proba = model.predict_proba(X_test_encoded)[:, 1]

(299844, 91) 0

#### Submission

In [9]:
save_submission(test_ids, test_proba, "log_reg_ohe.csv")

Saved to: C:\Users\Bharat\Desktop\remaining-2026\Career-Tracks\Track 01 - Data Science\Relevant Projects\airline-satisfaction-prediction\submissions\log_reg_ohe.csv
count    299844.000000
mean          0.443754
std           0.409263
min           0.000102
25%           0.038420
50%           0.257015
75%           0.918580
max           0.999579
Name: satisfaction, dtype: float64

            id  satisfaction
0       699635      0.115752
1       699636      0.889867
2       699637      0.614722
3       699638      0.029563
4       699639      0.013108
...        ...           ...
299839  999474      0.122978
299840  999475      0.009919
299841  999476      0.086229
299842  999477      0.032161
299843  999478      0.005018

[299844 rows x 2 columns]

### Decision Tree Baseline

In [7]:
saved_model = joblib.load(MODEL_DIR / "decision_tree_baseline.joblib")
state, model = saved_model["state"], saved_model["model"]

#### Necessary Preprocessing

In [8]:
X_test_encoded = apply_preprocessing(X_test, state)
print(X_test_encoded.shape, X_test_encoded.isna().sum().sum())

test_proba = model.predict_proba(X_test_encoded)[:, 1]

(299844, 91) 0

#### Submission

In [9]:
save_submission(test_ids, test_proba, "decision_tree.csv")

Saved to: C:\Users\Bharat\Desktop\remaining-2026\Career-Tracks\Track 01 - Data Science\Relevant Projects\airline-satisfaction-prediction\submissions\decision_tree.csv
count    299844.000000
mean          0.443626
std           0.426957
min           0.000000
25%           0.037424
50%           0.190852
75%           0.939109
max           1.000000
Name: satisfaction, dtype: float64

            id  satisfaction
0       699635      0.176159
1       699636      1.000000
2       699637      0.927305
3       699638      0.078146
4       699639      0.034269
...        ...           ...
299839  999474      0.044086
299840  999475      0.004425
299841  999476      0.265139
299842  999477      0.034269
299843  999478      0.034269

[299844 rows x 2 columns]

### Random Forest Baseline

In [6]:
tree = joblib.load(MODEL_DIR / "random_forest.joblib")
state, model = tree["state"], tree["model"]

### Necessary Preprocessing

In [7]:
X_test_encoded = apply_preprocessing(X_test, state)
print(X_test_encoded.shape, X_test_encoded.isna().sum().sum())

test_proba = model.predict_proba(X_test_encoded)[:, 1]

(299844, 91) 0

### Submission

In [8]:
save_submission(test_ids, test_proba, "random_forest.csv")

Saved to: C:\Users\Bharat\Desktop\remaining-2026\Career-Tracks\Track 01 - Data Science\Relevant Projects\airline-satisfaction-prediction\submissions\random_forest.csv
count    299844.000000
mean          0.443646
std           0.400293
min           0.022652
25%           0.050167
50%           0.242261
75%           0.923598
max           0.972156
Name: satisfaction, dtype: float64

            id  satisfaction
0       699635      0.299001
1       699636      0.825227
2       699637      0.729297
3       699638      0.082268
4       699639      0.058801
...        ...           ...
299839  999474      0.098519
299840  999475      0.052997
299841  999476      0.248849
299842  999477      0.045250
299843  999478      0.032211

[299844 rows x 2 columns]

### Random Forest without One Hot encoding for features

In [9]:
tree = joblib.load(MODEL_DIR / "random_forest_without_onehot.joblib")
state, model = tree["state"], tree["model"]

In [10]:
X_test_encoded = apply_preprocessing(X_test, state)
print(X_test_encoded.shape, X_test_encoded.isna().sum().sum())

test_proba = model.predict_proba(X_test_encoded)[:, 1]

(299844, 39) 0

In [11]:
save_submission(test_ids, test_proba, "random_forest_no_onehot.csv")

Saved to: C:\Users\Bharat\Desktop\remaining-2026\Career-Tracks\Track 01 - Data Science\Relevant Projects\airline-satisfaction-prediction\submissions\random_forest_no_onehot.csv
count    299844.000000
mean          0.443613
std           0.412586
min           0.018263
25%           0.040745
50%           0.231760
75%           0.935867
max           0.979816
Name: satisfaction, dtype: float64

            id  satisfaction
0       699635      0.255058
1       699636      0.853898
2       699637      0.735035
3       699638      0.067229
4       699639      0.046935
...        ...           ...
299839  999474      0.095693
299840  999475      0.053226
299841  999476      0.245263
299842  999477      0.034272
299843  999478      0.033309

[299844 rows x 2 columns]